FROM node:18.14.2-alpine AS builder
WORKDIR /app
COPY package*.json ./

# Python, 빌드 도구, libusb, linux-headers 및 eudev-dev 추가
RUN apk add --no-cache python3 make g++ libusb-dev linux-headers eudev-dev

RUN npm install
COPY . .
RUN npm run build

FROM node:18.14.2-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package*.json ./

# Python, 빌드 도구, libusb, linux-headers 및 eudev-dev 추가
RUN apk add --no-cache python3 make g++ libusb-dev linux-headers eudev-dev

RUN npm install --only=production

CMD ["npm", "run", "start:prod"]