export const QUERY_KEY = {
  GET_ALL_STRATEGY: 'GET_ALL_STRATEGY',
  GET_USED_COUNT: 'GET_USED_COUNT',
  GET_ALL_AGENT: 'GET_ALL_AGENT',
  GET_AGENT_METADATA: 'GET_AGENT_METADATA',
  GET_AGENT_STAT: 'GET_AGENT_STAT',
  GET_AGENT_PORTFOLIO_ACTIVITY: 'GET_AGENT_PORTFOLIO_ACTIVITY',
  GET_AGENT_PORTFOLIO_HOLDINGS: 'GET_AGENT_PORTFOLIO_HOLDINGS',
};

export const MUTATION_KEY = {
  LOGIN: 'LOGIN',
  CREATE_STRATEGY: 'CREATE_STRATEGY',
  DELETE_COOKIE: 'DELETE_COOKIE',
};

export const API_RESPONSE_CODE = {
  GET: 200,
  POST: 201,
  DELETE: 204,
  PATCH: 204,
};
